### ISSUE TITLE
Colisión con el camión

### ISSUE THREAD

**Issue by LeonardoTJ** [Proyecto-PP/Proyecto-POOA#2]
Arreglar colisiones.

**Comment by VictorVeraA** [comment]
La colisiones con el camion eran debidas a la secuencia en la que se realizaban las validaciones. El camion tiene un movimiento basado en la aceleracion del jugador (Esto debido a ciertas pruebas previas relacionadas con el movimiento del mapa). Se arreglo la secuencia haciendo que primero se reinicie a 0 la aceleracion del jugador y luego se verifique su posicion con respecto al camion.

El branch "ControlModifications" de "Proyecto-POOA"proporciona el codigo revisado y probado para la solucion de esta problematica.
